/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.titan.platform.wizards.newproject;

import java.io.File;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.WizardDescriptor;

public class ConfigurationPanelVisual extends JPanel implements DocumentListener {

    public static final String PROP_PROJECT_NAME = "projectName";
    private ConfigurationWizardPanel panel;

    public ConfigurationPanelVisual(ConfigurationWizardPanel panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        loginUrlLabel = new javax.swing.JLabel();
        cacheLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        urlField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cacheField = new javax.swing.JTextField();
        loginUrlField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        allSectionsCheck = new javax.swing.JCheckBox();
        debugModeCheck = new javax.swing.JCheckBox();
        useChatCheck = new javax.swing.JCheckBox();
        onlyFirefoxCheck = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, "Nome:");

        org.openide.awt.Mnemonics.setLocalizedText(descLabel, "Descrição:");

        org.openide.awt.Mnemonics.setLocalizedText(urlLabel, "Url:");

        org.openide.awt.Mnemonics.setLocalizedText(emailLabel, "Email:");

        org.openide.awt.Mnemonics.setLocalizedText(loginUrlLabel, "Login Url:");

        org.openide.awt.Mnemonics.setLocalizedText(cacheLabel, "Caminho Cache:");

        org.openide.awt.Mnemonics.setLocalizedText(findButton, "Procurar...");

        org.openide.awt.Mnemonics.setLocalizedText(allSectionsCheck, "all-sections");
        allSectionsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSectionsCheckActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(debugModeCheck, "debug-mode");

        org.openide.awt.Mnemonics.setLocalizedText(useChatCheck, "use-chat");
        useChatCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useChatCheckActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(onlyFirefoxCheck, "only-firefox");
        onlyFirefoxCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlyFirefoxCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(debugModeCheck)
                        .addGap(29, 29, 29)
                        .addComponent(useChatCheck)
                        .addGap(39, 39, 39)
                        .addComponent(allSectionsCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(onlyFirefoxCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlLabel)
                            .addComponent(descLabel)
                            .addComponent(nameLabel)
                            .addComponent(cacheLabel)
                            .addComponent(emailLabel)
                            .addComponent(loginUrlLabel))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(urlField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(loginUrlField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(cacheField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))))
                .addGap(70, 70, 70)
                .addComponent(findButton)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(findButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(80, 80, 80)))
                            .addComponent(loginUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(cacheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(nameLabel)
                            .addGap(18, 18, 18)
                            .addComponent(descLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                            .addComponent(urlLabel)
                            .addGap(29, 29, 29)
                            .addComponent(emailLabel)
                            .addGap(29, 29, 29)
                            .addComponent(loginUrlLabel)
                            .addGap(42, 42, 42)
                            .addComponent(cacheLabel))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debugModeCheck)
                    .addComponent(allSectionsCheck)
                    .addComponent(useChatCheck)
                    .addComponent(onlyFirefoxCheck))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allSectionsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSectionsCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allSectionsCheckActionPerformed

    private void useChatCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useChatCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useChatCheckActionPerformed

    private void onlyFirefoxCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlyFirefoxCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlyFirefoxCheckActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allSectionsCheck;
    private javax.swing.JTextField cacheField;
    private javax.swing.JLabel cacheLabel;
    private javax.swing.JCheckBox debugModeCheck;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField loginUrlField;
    private javax.swing.JLabel loginUrlLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JCheckBox onlyFirefoxCheck;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JCheckBox useChatCheck;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
    }

    @Override
    public void insertUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void removeUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void changedUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    void store(WizardDescriptor d) {
        String name = nameField.getText().trim();
        String desc = descField.getText().trim();
        String url = urlField.getText().trim();
        String email = emailField.getText().trim();
        String loginUrl = loginUrlField.getText().trim();
        String cachePath = cacheField.getText().trim();
        String debugMode = "false";
        String useChat = "false";
        String allSections = "false";
        String onlyFirefox = "false";

        if(debugModeCheck.isSelected()){
            debugMode = "true";
        }
        if(useChatCheck.isSelected()){
            useChat = "true";
        }
        if(allSectionsCheck.isSelected()){
            allSections = "true";
        }
        if(onlyFirefoxCheck.isSelected()){
            onlyFirefox = "true";
        }

        d.putProperty("name", name);
        d.putProperty("desc", desc);
        d.putProperty("url", url);
        d.putProperty("email", email);
        d.putProperty("loginUrl", loginUrl);
        d.putProperty("cachePath", new File(cachePath));
        d.putProperty("debugMode", debugMode);
        d.putProperty("useChat", useChat);
        d.putProperty("allSections", allSections);
        d.putProperty("onlyFirefox", onlyFirefox);
    }
}
