/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.titan.platform.wizards.newproject;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.WizardDescriptor;
import org.openide.filesystems.FileUtil;

public class ConfigurationPanelVisual extends JPanel implements DocumentListener {

    public static final String PROP_PROJECT_NAME = "projectName";
    private ConfigurationWizardPanel panel;

    public ConfigurationPanelVisual(ConfigurationWizardPanel panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        urlLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        loginUrlLabel = new javax.swing.JLabel();
        cacheLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        urlField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cacheField = new javax.swing.JTextField();
        loginUrlField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        debugModeCheck = new javax.swing.JCheckBox();
        useChatCheck = new javax.swing.JCheckBox();
        onlyFirefoxCheck = new javax.swing.JCheckBox();
        allSectionsCheck = new javax.swing.JCheckBox();
        cacheLabel1 = new javax.swing.JLabel();
        logoPathField = new javax.swing.JTextField();
        findLogoButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(551, 315));

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, "Nome:");

        org.openide.awt.Mnemonics.setLocalizedText(descLabel, "Descrição:");

        org.openide.awt.Mnemonics.setLocalizedText(urlLabel, "Url:");

        org.openide.awt.Mnemonics.setLocalizedText(emailLabel, "Email:");

        org.openide.awt.Mnemonics.setLocalizedText(loginUrlLabel, "Login Url:");

        org.openide.awt.Mnemonics.setLocalizedText(cacheLabel, "Caminho Cache:");

        urlField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                urlFieldFocusLost(evt);
            }
        });

        cacheField.setText("cache/");

        org.openide.awt.Mnemonics.setLocalizedText(findButton, "Procurar...");
        findButton.setActionCommand("BROWSE");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCacheButtonActionPerformed(evt);
            }
        });

        debugModeCheck.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(debugModeCheck, "modo debug");

        org.openide.awt.Mnemonics.setLocalizedText(useChatCheck, "usar chat");
        useChatCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useChatCheckActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(onlyFirefoxCheck, "somente firefox");
        onlyFirefoxCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlyFirefoxCheckActionPerformed(evt);
            }
        });

        allSectionsCheck.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(allSectionsCheck, "todas as sessões");

        org.openide.awt.Mnemonics.setLocalizedText(cacheLabel1, "Logo:");

        org.openide.awt.Mnemonics.setLocalizedText(findLogoButton, "Procurar...");
        findLogoButton.setActionCommand("BROWSE");
        findLogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(debugModeCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(useChatCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allSectionsCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onlyFirefoxCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginUrlLabel)
                            .addComponent(nameLabel)
                            .addComponent(descLabel)
                            .addComponent(urlLabel)
                            .addComponent(emailLabel)
                            .addComponent(cacheLabel)
                            .addComponent(cacheLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(logoPathField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(findLogoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginUrlField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(urlField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(descField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(cacheField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addComponent(findButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlLabel)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUrlLabel)
                    .addComponent(loginUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cacheLabel)
                    .addComponent(cacheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cacheLabel1)
                    .addComponent(logoPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findLogoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useChatCheck)
                    .addComponent(allSectionsCheck)
                    .addComponent(onlyFirefoxCheck)
                    .addComponent(debugModeCheck))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useChatCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useChatCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useChatCheckActionPerformed

    private void onlyFirefoxCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlyFirefoxCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlyFirefoxCheckActionPerformed

    private void browseCacheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCacheButtonActionPerformed
        String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            JFileChooser chooser = new JFileChooser();
            FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            chooser.setDialogTitle("Select Repos Location");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            String path = this.cacheField.getText();
            if (path.length() > 0) {
                File f = new File(path);
                if (f.exists()) {
                    chooser.setSelectedFile(f);
                }
            }
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File projectDir = chooser.getSelectedFile();
                cacheField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
            }
            panel.fireChangeEvent();
        }
    }//GEN-LAST:event_browseCacheButtonActionPerformed

    private void urlFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlFieldFocusLost
        if(urlField.getText().trim().length() > 0){
            loginUrlField.setText(urlField.getText().trim()+"/titan.php?target=login");
        }
        else{
               loginUrlField.setText("");
        }
    }//GEN-LAST:event_urlFieldFocusLost

    private void fileLogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLogoButtonActionPerformed
       String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            JFileChooser chooser = new JFileChooser();
            FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            chooser.setDialogTitle("Select logo Location");
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            String path = this.logoPathField.getText();
            if (path.length() > 0) {
                File f = new File(path);
                if (f.exists()) {
                    chooser.setSelectedFile(f);
                }
            }
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File projectDir = chooser.getSelectedFile();
                logoPathField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
            }
            panel.fireChangeEvent();
        }
    }//GEN-LAST:event_fileLogoButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allSectionsCheck;
    private javax.swing.JTextField cacheField;
    private javax.swing.JLabel cacheLabel;
    private javax.swing.JLabel cacheLabel1;
    private javax.swing.JCheckBox debugModeCheck;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton findButton;
    private javax.swing.JButton findLogoButton;
    private javax.swing.JTextField loginUrlField;
    private javax.swing.JLabel loginUrlLabel;
    private javax.swing.JTextField logoPathField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JCheckBox onlyFirefoxCheck;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JCheckBox useChatCheck;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
    }
    boolean valid(WizardDescriptor wizardDescriptor) {

        wizardDescriptor.putProperty("WizardPanel_errorMessage", "");
        return true;
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
    }

   private void updateTexts(DocumentEvent e) {
        panel.fireChangeEvent(); // Notify that the panel changed
   }

    void store(WizardDescriptor d) {
        String name = nameField.getText().trim();
        String desc = descField.getText().trim();
        String url = urlField.getText().trim();
        String email = emailField.getText().trim();
        String loginUrl = loginUrlField.getText().trim();
        String cachePath = cacheField.getText().trim();
        String debugMode = "false";
        String useChat = "false";
        String allSections = "false";
        String onlyFirefox = "false";

        if(debugModeCheck.isSelected()){
            debugMode = "true";
        }
        if(useChatCheck.isSelected()){
            useChat = "true";
        }
        if(allSectionsCheck.isSelected()){
            allSections = "true";
        }
        if(onlyFirefoxCheck.isSelected()){
            onlyFirefox = "true";
        }

        d.putProperty("name", name);
        d.putProperty("desc", desc);
        d.putProperty("url", url);
        d.putProperty("email", email);
        d.putProperty("loginUrl", loginUrl);
        d.putProperty("cachePath", new File(cachePath));
        d.putProperty("debugMode", debugMode);
        d.putProperty("useChat", useChat);
        d.putProperty("allSections", allSections);
        d.putProperty("onlyFirefox", onlyFirefox);
    }

    void read(WizardDescriptor settings) {
        //
    }
}
