/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.titan.platform.wizards.newproject;

import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.WizardDescriptor;
import org.openide.util.Exceptions;
import org.titan.platform.wizards.components.ImportProgressBar;
import static org.titan.platform.utils.Utils.bundle;

public class DataBasePanelVisual extends JPanel implements DocumentListener {

    public static final String PROP_PROJECT_NAME = "projectName";
    private DatabaseWizardPanel panel;

    public DataBasePanelVisual(DatabaseWizardPanel panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sgbdLabel = new javax.swing.JLabel();
        HostLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        schemaLabel = new javax.swing.JLabel();
        sgdbField = new javax.swing.JTextField();
        hostField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        schemaField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        ImportButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "jLabel1");

        org.openide.awt.Mnemonics.setLocalizedText(sgbdLabel, "Sgdb:");

        org.openide.awt.Mnemonics.setLocalizedText(HostLabel, "Host:");

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, bundle(this.getClass(),"label.database.name"));

        org.openide.awt.Mnemonics.setLocalizedText(userLabel, bundle(this.getClass(),"label.database.user"));

        org.openide.awt.Mnemonics.setLocalizedText(portLabel, bundle(this.getClass(),"label.database.port"));

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, bundle(this.getClass(),"label.database.password"));

        org.openide.awt.Mnemonics.setLocalizedText(schemaLabel, "Schema:");

        sgdbField.setEditable(false);
        sgdbField.setText("PostgreSQL");

        hostField.setText("localhost");

        portField.setText("5432");

        schemaField.setEditable(false);
        schemaField.setText("titan");

        org.openide.awt.Mnemonics.setLocalizedText(ImportButton, bundle(this.getClass(),"label.database.import"));
        ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImportButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sgbdLabel)
                            .addComponent(HostLabel)
                            .addComponent(nameLabel)
                            .addComponent(schemaLabel)
                            .addComponent(passwordLabel)
                            .addComponent(userLabel)
                            .addComponent(portLabel))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(userField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(portField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(schemaField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(sgdbField, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgbdLabel)
                    .addComponent(sgdbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostLabel)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schemaLabel)
                    .addComponent(schemaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ImportButton)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportButtonActionPerformed

        importProgressBar = new ImportProgressBar();

        Thread threadImport = new Thread(new Runnable(){
            
            public void run(){

                try {
                    panel.importDatabase(nameField.getText(), userField.getText(), passwordField.getText());
                    importProgressBar.close();

                }catch (IOException ex) {
                    importProgressBar.close();
                     ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao Importar Banco", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException ex) {
                    importProgressBar.close();
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao Importar Banco", JOptionPane.ERROR_MESSAGE);
                }

            }
        });

        threadImport.start();

        importProgressBar.setModal(true);
        importProgressBar.setVisible(true);



    }//GEN-LAST:event_ImportButtonActionPerformed
    ImportProgressBar importProgressBar = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HostLabel;
    private javax.swing.JButton ImportButton;
    private javax.swing.JTextField hostField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField portField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField schemaField;
    private javax.swing.JLabel schemaLabel;
    private javax.swing.JLabel sgbdLabel;
    private javax.swing.JTextField sgdbField;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
    }

    @Override
    public void insertUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void removeUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void changedUpdate(DocumentEvent de) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    void store(WizardDescriptor d) {
        String sgdb = sgdbField.getText().trim();
        String host = hostField.getText().trim();
        String name = nameField.getText().trim();
        String user = userField.getText().trim();
        String port = portField.getText().trim();
        String password = passwordField.getText().trim();
        String schema = schemaField.getText().trim();

        d.putProperty("sgdb", sgdb);
        d.putProperty("host", host);
        d.putProperty("databaseName", name);
        d.putProperty("user", user);
        d.putProperty("port", port);
        d.putProperty("password", password);
        d.putProperty("schema", schema);

    }
}
